version: "3.1"

services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    volumes:
      - "mc:/data"
    environment:
      EULA: "TRUE"
      TZ: "America/Chicago"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "testing"
      RCON_PORT: 28016
      ENFORCE_WHITELIST: "TRUE"
      WHITELIST: user1,user2
    restart: always

volumes:
  mc:
